### ISSUE TITLE
Help needed to integrate with doom-mode-line

### ISSUE THREAD

**Issue by ChetanKoneru** [Javyre/winds.el#1]
Hi I am trying to integrate `winds.el` with `doom-mode-line`. To do that the below function needs to be redefined. 

```
(doom-modeline-def-segment workspace-name
  "The current workspace name or number.
Requires `eyebrowse-mode' or `tab-bar-mode' to be enabled."
  (when-let
      ((name (cond
              ((and (bound-and-true-p eyebrowse-mode)
                    (< 1 (length (eyebrowse--get 'window-configs))))
               (assq-delete-all 'eyebrowse-mode mode-line-misc-info)
               (when-let*
                   ((num (eyebrowse--get 'current-slot))
                    (tag (nth 2 (assoc num (eyebrowse--get 'window-configs)))))
                 (if (< 0 (length tag)) tag (int-to-string num))))
              ((bound-and-true-p tab-bar-mode)
               (let* ((current-tab (tab-bar--current-tab))
                      (tab-index (tab-bar--current-tab-index))
                      (explicit-name (alist-get 'explicit-name current-tab))
                      (tab-name (alist-get 'name current-tab)))
                 (if explicit-name tab-name (+ 1 tab-index)))))))
    (propertize (format " %s " name) 'face
                (if (doom-modeline--active)
                    'doom-modeline-buffer-major-mode
                  'mode-line-inactive))))
```

I am very new to emacs and have trouble to re-engineer this code for `winds.el`.
Can I ask your to help with it. Thanks

**Comment by Javyre** [comment]
Hey, sorry for the late response. Here's my first impression:

`winds.el` doesn't define any minor modes so checking for the feature is enough to know if it's active.

I'm assuming the behavior you're looking for is for the mode-line to show the current workspace.

I don't use doom but the following should work:

```elisp
(doom-modeline-def-segment workspace-name
  "The current workspace name or number.
Requires `winds.el' to be loaded, or `eyebrowse-mode' or
`Requires tab-bar-mode' to be enabled."
  (when-let
      ((name (cond
              ((featurep 'winds)
               (format "%s|%s" (winds-get-cur-ws) (winds-get-cur-cfg)))

              ((and (bound-and-true-p eyebrowse-mode)
                    (< 1 (length (eyebrowse--get 'window-configs))))
               (assq-delete-all 'eyebrowse-mode mode-line-misc-info)
               (when-let*
                   ((num (eyebrowse--get 'current-slot))
                    (tag (nth 2 (assoc num (eyebrowse--get 'window-configs)))))
                 (if (< 0 (length tag)) tag (int-to-string num))))

              ((bound-and-true-p tab-bar-mode)
               (let* ((current-tab (tab-bar--current-tab))
                      (tab-index (tab-bar--current-tab-index))
                      (explicit-name (alist-get 'explicit-name current-tab))
                      (tab-name (alist-get 'name current-tab)))
                 (if explicit-name tab-name (+ 1 tab-index)))))))

    (propertize (format " %s " name) 'face
                (if (doom-modeline--active)
                    'doom-modeline-buffer-major-mode
                  'mode-line-inactive))))
```

**Comment by ChetanKoneru** [comment]
@Javyre Thanks. No worries, I will try that out and let you know.

**Comment by ChetanKoneru** [comment]
That works great Thanks. Creating a pull request for doom-mode-line

**Comment by Javyre** [comment]
Cool. I saw the pull request.
I might chime in on the pr if there are any unanswered questions, but keep in mind that `winds.el` is relatively young still. The way it originally worked was that if you had it installed and loaded, then you had it enabled. This was because there was no need to set any hooks or significant initialization for `winds.el`.

Now, I'm fixing some bugs and consistency issues (especially for better multi-frame support) and I'm starting to see a real need for a global minor mode to be defined. 

What this means for the mode-line code is the detection code may change to something more like `(bound-and-true-p winds-mode)`.

(I am also planning to soon add a nicknaming feature to give names to workspaces/cfgs, so you might want to also integrate that into the mod-eline segment when it comes out)

**Comment by ChetanKoneru** [comment]
@Javyre , Thanks. Yes I have done the `(bound-and-true-p winds-mode)` . 

Apart from that I did not have time to sit down and look into the code. I am relatively new to emacs lisp and my work is keeping me busy to look in to it. Please feel free to look in to the PR for doom-mode-line.

Again thanks for the package and support.

**Comment by Javyre** [comment]
Yeah so `bound-and-true-p` should work fine as of https://github.com/Javyre/winds.el/commit/d5c13c321a9af03b025c200a03562047cbc5087c

(About the nicknaming feature, I don't have that as a very important priority for me so it may come much later. `winds.el` should be stable for some time now.)
